<header class="main-header">
    <!-- Logo -->
  <a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>bu</b><i>wo</i></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>budget</b><i>worm</i></span>
  </a>
    <!-- include header navbar -->
    <?php include('./headernavbar.inc');?>
</header>
