<aside class="main-sidebar">
<!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
        <li class="header">NAVIGATION</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="./budgets_overview.php"><i class="fa fa-link"></i> <span>Budgets Overview</span></a></li>
        <li class="treeview">
          <a href="#"><i class="fa fa-link"></i> <span>Bookings</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
            <ul class="treeview-menu">
              <li><a href="#">Overview</a></li>
              <li><a href="#">Add new booking</a></li>
            </ul>
          </li>
        </ul>
      <!-- /.sidebar-menu -->
    </section>
  <!-- /.sidebar -->
</aside>
